# Generated by Django 2.0.1 on 2018-01-12 13:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180112_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 13, 27, 26, 193949, tzinfo=utc), verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
